sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t charliegilman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true charliegilman/docker-react yarn test -- --coverage
